package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"

	"github.com/Nguyen-Tan-Dat/Vocabularies-Learning-API/graph"
)

// Hello is the resolver for the hello field.
func (r *mutationResolver) Hello(ctx context.Context, name string) (string, error) {
	panic(fmt.Errorf("not implemented: Hello - hello"))
}

// Index is the resolver for the index field.
func (r *queryResolver) Index(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Index - index"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
