package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/Nguyen-Tan-Dat/Vocabularies-Learning-API/graph/model"
)

// CreateEnglish is the resolver for the createEnglish field.
func (r *mutationResolver) CreateEnglish(ctx context.Context, input model.NewEnglishInput) (*model.English, error) {
	return r.EnglishService.Create(
		ctx,
		&input,
	)
}

// UpdateEnglish is the resolver for the updateEnglish field.
func (r *mutationResolver) UpdateEnglish(ctx context.Context, input model.UpdateEnglishInput) (*model.English, error) {
	return r.EnglishService.Update(
		ctx,
		&input,
	)
}

// DeleteEnglish is the resolver for the deleteEnglish field.
func (r *mutationResolver) DeleteEnglish(ctx context.Context, id int32) (bool, error) {
	if err := r.EnglishService.Delete(
		ctx,
		int(id),
	); err != nil {

		return false, err
	}

	return true, nil
}

// English is the resolver for the english field.
func (r *queryResolver) English(ctx context.Context, id int32) (*model.English, error) {
	return r.EnglishService.GetByID(
		ctx,
		int(id),
	)
}

// EnglishList is the resolver for the englishList field.
func (r *queryResolver) EnglishList(ctx context.Context) ([]*model.English, error) {
	return r.EnglishService.GetAll(ctx)
}
