package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/Nguyen-Tan-Dat/Vocabularies-Learning-API/graph/model"
)

// EnglishList is the resolver for the englishList field.
func (r *queryResolver) EnglishList(ctx context.Context) ([]*model.English, error) {
	return r.EnglishService.GetAll(ctx)
}

// SearchEnglish is the resolver for the searchEnglish field.
func (r *queryResolver) SearchEnglish(ctx context.Context, word string) ([]*model.English, error) {
	return r.EnglishService.Search(ctx, word)
}
