package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/Nguyen-Tan-Dat/Vocabularies-Learning-API/graph/model"
)

// CreateTopic is the resolver for the createTopic field.
func (r *mutationResolver) CreateTopic(ctx context.Context, input model.NewTopicInput) (*model.Topic, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.TopicService.CreateTopic(ctx, input.Name, userID)
}

// UpdateTopic is the resolver for the updateTopic field.
func (r *mutationResolver) UpdateTopic(ctx context.Context, input model.UpdateTopicInput) (*model.Topic, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.TopicService.Update(ctx, userID, input)
}

// DeleteTopic is the resolver for the deleteTopic field.
func (r *mutationResolver) DeleteTopic(ctx context.Context, id int32) (bool, error) {
	if err := r.TopicService.Delete(ctx, int(id)); err != nil {
		return false, err
	}
	return true, nil
}

// Topics is the resolver for the topics field.
func (r *queryResolver) Topics(ctx context.Context) ([]*model.Topic, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.TopicService.GetTopics(ctx, userID)
}

// Topic is the resolver for the topic field.
func (r *queryResolver) Topic(ctx context.Context, id int32) (*model.Topic, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.TopicService.Get(ctx, userID, id)
}

// SearchTopics is the resolver for the searchTopics field.
func (r *queryResolver) SearchTopics(ctx context.Context, keyword string) ([]*model.Topic, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.TopicService.Search(ctx, userID, keyword)
}
