package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/Nguyen-Tan-Dat/Vocabularies-Learning-API/graph/model"
)

// CreateVietnamese is the resolver for the createVietnamese field.
func (r *mutationResolver) CreateVietnamese(ctx context.Context, input model.NewVietnameseInput) (*model.Vietnamese, error) {
	panic(fmt.Errorf("not implemented: CreateVietnamese - createVietnamese"))
}

// UpdateVietnamese is the resolver for the updateVietnamese field.
func (r *mutationResolver) UpdateVietnamese(ctx context.Context, input model.UpdateVietnameseInput) (*model.Vietnamese, error) {
	panic(fmt.Errorf("not implemented: UpdateVietnamese - updateVietnamese"))
}

// DeleteVietnamese is the resolver for the deleteVietnamese field.
func (r *mutationResolver) DeleteVietnamese(ctx context.Context, id int32) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteVietnamese - deleteVietnamese"))
}

// GetVietnamese is the resolver for the getVietnamese field.
func (r *queryResolver) GetVietnamese(ctx context.Context, id int32) (*model.Vietnamese, error) {
	panic(fmt.Errorf("not implemented: GetVietnamese - getVietnamese"))
}

// ListVietnamese is the resolver for the listVietnamese field.
func (r *queryResolver) ListVietnamese(ctx context.Context, userID int32) ([]*model.Vietnamese, error) {
	panic(fmt.Errorf("not implemented: ListVietnamese - listVietnamese"))
}
