// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type English struct {
	ID           int32   `json:"id"`
	Word         string  `json:"word"`
	Definition   *string `json:"definition,omitempty"`
	PartOfSpeech *string `json:"partOfSpeech,omitempty"`
	Example      *string `json:"example,omitempty"`
	UserID       int32   `json:"userId"`
}

type Mutation struct {
}

type NewEnglishInput struct {
	Word         string  `json:"word"`
	Definition   *string `json:"definition,omitempty"`
	PartOfSpeech *string `json:"partOfSpeech,omitempty"`
	Example      *string `json:"example,omitempty"`
	UserID       int32   `json:"userId"`
}

type NewTopic struct {
	Name   string `json:"name"`
	UserID int32  `json:"userId"`
}

type Query struct {
}

type Topic struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	UserID int32  `json:"userId"`
}

type UpdateEnglishInput struct {
	ID           int32   `json:"id"`
	Word         *string `json:"word,omitempty"`
	Definition   *string `json:"definition,omitempty"`
	PartOfSpeech *string `json:"partOfSpeech,omitempty"`
	Example      *string `json:"example,omitempty"`
}

type UpdateTopicInput struct {
	ID   int32   `json:"id"`
	Name *string `json:"name,omitempty"`
}
