// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTopic struct {
	Name   string `json:"name"`
	UserID int32  `json:"userId"`
}

type Query struct {
}

type Topic struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	UserID int32  `json:"userId"`
}

type UpdateTopicInput struct {
	ID   int32   `json:"id"`
	Name *string `json:"name,omitempty"`
}
