// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type English struct {
	ID       int32   `json:"id"`
	Word     string  `json:"word"`
	Phonetic *string `json:"phonetic,omitempty"`
	Audio    *string `json:"audio,omitempty"`
}

type Mutation struct {
}

type NewEnglishInput struct {
	Word     string  `json:"word"`
	Phonetic *string `json:"phonetic,omitempty"`
	Audio    *string `json:"audio,omitempty"`
}

type NewTopicInput struct {
	Name string `json:"name"`
}

type Query struct {
}

type Topic struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	OfUser int32  `json:"ofUser"`
}

type UpdateEnglishInput struct {
	ID       int32   `json:"id"`
	Word     *string `json:"word,omitempty"`
	Phonetic *string `json:"phonetic,omitempty"`
	Audio    *string `json:"audio,omitempty"`
}

type UpdateTopicInput struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	OfUser int32  `json:"ofUser"`
}
